In [27]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression as LR
from sklearn.metrics import confusion_matrix as CM
from sklearn.metrics import accuracy_score

Step 1 Import dataset and do the cleaning

In [50]:
# Import the orginial dataset
train = pd.read_csv('/content/sample_data/fashion_train.csv', header = None)
test = pd.read_csv('/content/sample_data/fashion_test.csv', header = None)

In [53]:
train.head()
# test.head()

0    1    2    3    4    5    6    ...  778  779  780  781  782  783  784
0    9    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1    0    0    0    0    0    0    1  ...   76    0    0    0    0    0    0
2    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3    3    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[5 rows x 785 columns]

In [29]:
# Rename the first column as 'initial' to stands for original labels
train.rename(columns={0:'initial'}, inplace=True)
test.rename(columns={0:'initial'}, inplace=True)
print(train)
print(test)

       initial  1  2  3  4  5  6  7  ...  777  778  779  780  781  782  783  784
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
1            0  0  0  0  0  0  1  0  ...  130   76    0    0    0    0    0    0
2            0  0  0  0  0  0  0  0  ...    1    0    0    0    0    0    0    0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0
59998        0  0  0  0  0  0  0  0  ...   50    5    0    1    0    0    0    0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0    0

[60000 rows x 785 columns]


Step 2 Relabel 10 different digits with one-hot encoding

In [30]:
######### relabel 0 ########
### train_zero
train_zero = train
train_zero['relabel'] = 0
train_zero.loc[train_zero['initial']==0,'relabel']=1 # replace label 0 as 1, label m as 0
print(train_zero)
### test_zero
test_zero = test
test_zero['relabel'] = 0
test_zero.loc[test_zero['initial']==0,'relabel']=1 # set label 0 as 1, label m as 0
print(test_zero)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        1
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        1
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        1
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        1
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [31]:
######### relabel 1 ########
### train_one
train_one = train
train_one['relabel'] = 0
train_one.loc[train_one['initial']==1,'relabel']=1 # replace label 1 as 1, label m as 0
print(train_one)
### test_one
test_one = test
test_one['relabel'] = 0
test_one.loc[test_one['initial']==1,'relabel']=1 # set label 1 as 1, label m as 0
print(test_one)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        1
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [32]:
######### relabel 2 ########
### train_two
train_two = train
train_two['relabel'] = 0
train_two.loc[train_two['initial']==2,'relabel']=1 # replace label 2 as 1, label m as 0
print(train_two)
### test_two
test_two = test
test_two['relabel'] = 0
test_two.loc[test_two['initial']==2,'relabel']=1 # set label 2 as 1, label m as 0
print(test_two)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [33]:
######### relabel 3 ########
### train_three
train_three = train
train_three['relabel'] = 0
train_three.loc[train_three['initial']==3,'relabel']=1 # replace label 3 as 1, label m as 0
print(train_three)
### test_three
test_three = test
test_three['relabel'] = 0
test_three.loc[test_three['initial']==3,'relabel']=1 # set label 3 as 1, label m as 0
print(test_three)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        1
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        1
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [34]:
######### relabel 4 ########
### train_four
train_four = train
train_four['relabel'] = 0
train_four.loc[train_four['initial']==4,'relabel']=1 # replace label 4 as 1, label m as 0
print(train_four)
### test_four
test_four = test
test_four['relabel'] = 0
test_four.loc[test_four['initial']==4,'relabel']=1 # set label 4 as 1, label m as 0
print(test_four)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [35]:
######### relabel 5 ########
### train_five
train_five = train
train_five['relabel'] = 0
train_five.loc[train_five['initial']==5,'relabel']=1 # replace label 5 as 1, label m as 0
print(train_five)
### test_five
test_five = test
test_five['relabel'] = 0
test_five.loc[test_five['initial']==5,'relabel']=1 # set label 5 as 1, label m as 0
print(test_five)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        1
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [36]:
######### relabel 6 ########
### train_six
train_six = train
train_six['relabel'] = 0
train_six.loc[train_six['initial']==6,'relabel']=1 # replace label 6 as 1, label m as 0
print(train_six)
### test_six
test_six = test
test_six['relabel'] = 0
test_six.loc[test_six['initial']==6,'relabel']=1 # set label 6 as 1, label m as 0
print(test_six)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [37]:
######### relabel 7 ########
### train_seven
train_seven = train
train_seven['relabel'] = 0
train_seven.loc[train_seven['initial']==7,'relabel']=1 # replace label 7 as 1, label m as 0
print(train_seven)
### test_seven
test_seven = test
test_seven['relabel'] = 0
test_seven.loc[test_seven['initial']==7,'relabel']=1 # set label 7 as 1, label m as 0
print(test_seven)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [38]:
######### relabel 8 ########
### train_eight
train_eight = train
train_eight['relabel'] = 0
train_eight.loc[train_eight['initial']==8,'relabel']=1 # replace label 8 as 1, label m as 0
print(train_eight)
### test_eight
test_eight = test
test_eight['relabel'] = 0
test_eight.loc[test_eight['initial']==8,'relabel']=1 # set label 8 as 1, label m as 0
print(test_eight)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

In [39]:
######### relabel 9 ########
### train_nine
train_nine = train
train_nine['relabel'] = 0
train_nine.loc[train_nine['initial']==9,'relabel']=1 # replace label 9 as 1, label m as 0
print(train_nine)
### test_nine
test_nine = test
test_nine['relabel'] = 0
test_nine.loc[test_nine['initial']==9,'relabel']=1 # set label 9 as 1, label m as 0
print(test_nine)

       initial  1  2  3  4  5  6  7  ...  778  779  780  781  782  783  784  relabel
0            9  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        1
1            0  0  0  0  0  0  1  0  ...   76    0    0    0    0    0    0        0
2            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
3            3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
4            0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
...        ... .. .. .. .. .. .. ..  ...  ...  ...  ...  ...  ...  ...  ...      ...
59995        5  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59996        1  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59997        3  0  0  0  0  0  0  0  ...    0    0    0    0    0    0    0        0
59998        0  0  0  0  0  0  0  0  ...    5    0    1    0    0    0    0        0
59999        5  0  0  0  0  0  0  0  ...    0    0    0    0    0

Step 3 define training X, training Y, testing X and testing Y

In [40]:
### train x
train_zero_x = train_zero.iloc[:,1:785]
train_one_x = train_one.iloc[:,1:785]
train_two_x = train_two.iloc[:,1:785]
train_three_x = train_three.iloc[:,1:785]
train_four_x = train_four.iloc[:,1:785]
train_five_x = train_five.iloc[:,1:785]
train_six_x = train_six.iloc[:,1:785]
train_seven_x = train_seven.iloc[:,1:785]
train_eight_x = train_eight.iloc[:,1:785]
train_nine_x = train_nine.iloc[:,1:785]

   1    2    3    4    5    6    7    ...  778  779  780  781  782  783  784
0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1    0    0    0    0    0    1    0  ...   76    0    0    0    0    0    0
2    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[5 rows x 784 columns]


In [41]:
### train y
train_zero_y = train_zero['relabel']
train_one_y = train_one['relabel']
train_two_y = train_two['relabel']
train_three_y = train_three['relabel']
train_four_y = train_four['relabel']
train_five_y = train_five['relabel']
train_six_y = train_six['relabel']
train_seven_y = train_seven['relabel']
train_eight_y = train_eight['relabel']
train_nine_y = train_nine['relabel']

(60000,)

In [42]:
# test x
test_zero_x = test_zero.iloc[:,1:785]
test_one_x = test_one.iloc[:,1:785]
test_two_x = test_two.iloc[:,1:785]
test_three_x = test_three.iloc[:,1:785]
test_four_x = test_four.iloc[:,1:785]
test_five_x = test_five.iloc[:,1:785]
test_six_x = test_six.iloc[:,1:785]
test_seven_x = test_seven.iloc[:,1:785]
test_eight_x = test_eight.iloc[:,1:785]
test_nine_x = test_nine.iloc[:,1:785]

   1    2    3    4    5    6    7    ...  778  779  780  781  782  783  784
0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1    0    0    0    0    0    0    0  ...    3  174  189   67    0    0    0
2    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4    0    0    0    2    0    1    1  ...    0    0    0    0    0    0    0

[5 rows x 784 columns]


In [43]:
# test y
test_zero_y = test_zero['relabel']
test_one_y = test_one['relabel']
test_two_y = test_two['relabel']
test_three_y = test_three['relabel']
test_four_y = test_four['relabel']
test_five_y = test_five['relabel']
test_six_y = test_six['relabel']
test_seven_y = test_seven['relabel']
test_eight_y = test_eight['relabel']
test_nine_y = test_nine['relabel']

(10000,)

Step 4 Logistics Regression

In [44]:
clf_zero = LR(random_state=0).fit(train_zero_x, train_zero_y)
pred_zero = clf_zero.predict(test_zero_x)
clf_one = LR(random_state=0).fit(train_one_x, train_one_y)
pred_one = clf_one.predict(test_one_x)
clf_two = LR(random_state=0).fit(train_two_x, train_two_y)
pred_two = clf_two.predict(test_two_x)
clf_three = LR(random_state=0).fit(train_three_x, train_three_y)
pred_three = clf_three.predict(test_three_x)
clf_four = LR(random_state=0).fit(train_four_x, train_four_y)
pred_four = clf_four.predict(test_four_x)
clf_five = LR(random_state=0).fit(train_five_x, train_five_y)
pred_five = clf_five.predict(test_five_x)
clf_six = LR(random_state=0).fit(train_six_x, train_six_y)
pred_six = clf_six.predict(test_six_x)
clf_seven = LR(random_state=0).fit(train_seven_x, train_seven_y)
pred_seven = clf_seven.predict(test_seven_x)
clf_eight = LR(random_state=0).fit(train_eight_x, train_eight_y)
pred_eight = clf_eight.predict(test_eight_x)
clf_nine = LR(random_state=0).fit(train_nine_x, train_nine_y)
pred_nine = clf_nine.predict(test_nine_x)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


Step 6 Check the possibility matrix and accuracy score

In [48]:
## Check the possibility matrix for each pixcel ##
print(clf_zero.predict_proba(test_zero_x))
print(clf_one.predict_proba(test_one_x))
print(clf_two.predict_proba(test_two_x))
print(clf_three.predict_proba(test_three_x))
print(clf_four.predict_proba(test_four_x))
print(clf_five.predict_proba(test_five_x))
print(clf_six.predict_proba(test_six_x))
print(clf_seven.predict_proba(test_seven_x))
print(clf_eight.predict_proba(test_eight_x))
print(clf_nine.predict_proba(test_nine_x))

[[3.41672575e-01 6.58327425e-01]
 [1.00000000e+00 1.00691419e-29]
 [1.00000000e+00 1.49089472e-10]
 ...
 [9.99999998e-01 1.83874960e-09]
 [9.99974458e-01 2.55419417e-05]
 [9.99995748e-01 4.25213059e-06]]
[[3.41672575e-01 6.58327425e-01]
 [1.00000000e+00 1.00691419e-29]
 [1.00000000e+00 1.49089472e-10]
 ...
 [9.99999998e-01 1.83874960e-09]
 [9.99974458e-01 2.55419417e-05]
 [9.99995748e-01 4.25213059e-06]]
[[3.41672575e-01 6.58327425e-01]
 [1.00000000e+00 1.00691419e-29]
 [1.00000000e+00 1.49089472e-10]
 ...
 [9.99999998e-01 1.83874960e-09]
 [9.99974458e-01 2.55419417e-05]
 [9.99995748e-01 4.25213059e-06]]
[[3.41672575e-01 6.58327425e-01]
 [1.00000000e+00 1.00691419e-29]
 [1.00000000e+00 1.49089472e-10]
 ...
 [9.99999998e-01 1.83874960e-09]
 [9.99974458e-01 2.55419417e-05]
 [9.99995748e-01 4.25213059e-06]]
[[3.41672575e-01 6.58327425e-01]
 [1.00000000e+00 1.00691419e-29]
 [1.00000000e+00 1.49089472e-10]
 ...
 [9.99999998e-01 1.83874960e-09]
 [9.99974458e-01 2.55419417e-05]
 [9.99995748e-

Step 5 Confusion Matrix (CM)

In [49]:
CM_zero = CM(pred_zero,test_zero_y)
CM_one = CM(pred_one,test_one_y)
CM_two = CM(pred_two,test_two_y)
CM_three = CM(pred_three,test_three_y)
CM_four = CM(pred_four,test_four_y)
CM_five = CM(pred_five,test_five_y)
CM_six = CM(pred_six,test_six_y)
CM_seven = CM(pred_seven,test_seven_y)
CM_eight = CM(pred_eight,test_eight_y)
CM_nine = CM(pred_nine,test_nine_y)
print(CM_zero)
print(CM_one)
print(CM_two)
print(CM_three)
print(CM_four)
print(CM_five)
print(CM_six)
print(CM_eight)
print(CM_nine)

[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]
[[8913   74]
 [  87  926]]


In [47]:
####### Check the accuracy score #######
print(accuracy_score(pred_zero,test_zero_y))
print(accuracy_score(pred_one,test_one_y))
print(accuracy_score(pred_two,test_two_y))
print(accuracy_score(pred_three,test_three_y))
print(accuracy_score(pred_four,test_four_y))
print(accuracy_score(pred_five,test_five_y))
print(accuracy_score(pred_six,test_six_y))
print(accuracy_score(pred_seven,test_seven_y))
print(accuracy_score(pred_eight,test_eight_y))
print(accuracy_score(pred_nine,test_nine_y))

0.9839
0.9839
0.9839
0.9839
0.9839
0.9839
0.9839
0.9839
0.9839
0.9839
